java=float(input("enter a value"))
python=float(input("enter avalue"))
mysql=float(input("enter a value"))
print("total:",java+python+mysql)
print("average:",java+python+mysql/3)
print("percentage:",java+python+mysql/3*100)
print("remaining marks:",300-java+python+mysql)
